{ config, lib, pkgs, vars, ... }:

with lib;
{
  options = {
    dwm = {
      enable = mkOption {
        type = types.bool;
        default = false;
      };
    };
  };

  config = mkIf (config.dwm.enable) {
    programs = {
      zsh.enable = true;
    };

    services.xserver = {
      enable = true;
      autorun = true;
      displayManager = {
        startx.enable = true;
        defaultSession = "none+dwm";
      };
      libinput = {
        enable = true;
        touchpad = {
          naturalScrolling = true;
        };
      };
      windowManager.dwm = {
        enable = true;
        package = pkgs.dwm.overrideAttrs {
          src = pkgs.fetchFromGitHub {
            owner = "ebadfd";
            repo = "dwm";
            rev = "3f6cf3d0d511110fd4fba3c89722f289f15c89be";
            hash = "sha256-69iHYr2258idJdzvQOj2rxWSKDs3eENBQzK+UlVEpoI=";
          };
        };
      };
    };

    environment.etc = {
        "profile.local".text = 
	''
          # /etc/profile.local: DO NOT EDIT -- this file has been generated automatically.

          if [ -f "$HOME/.profile" ]; then
            . "$HOME/.profile"
          fi

          if [ -z "$DISPLAY" ] && [ "''${XDG_VTNR}" -eq 1 ]; then
            exec startx
          fi
        '';
    };

    home-manager.users.${vars.user} = {
      home = {
        file.".xinitrc" = {
          executable = true;
          text = # bash
            ''
            # .xinitrc autogenerated. Do not edit

            # firefox xserver variable
            export MOZ_USE_XINPUT2=1;
            '';
        };
      };
    };
  };
}

