[
  ./yabai.nix
  ./zsh.nix
  ../../modules/editors/nvim.nix
  ../../modules/theming/stylix.nix
  ../../modules/programs/tmux.nix
  ../../modules/programs/git.nix
  ../../modules/programs/bitwaden.nix
  ../../modules/programs/firefox.nix
  ../../modules/programs/chromium.nix
  ../../modules/programs/alacritty.nix
]
