[
  ./yabai.nix
  ./zsh.nix
  ../../modules/editors/nvim.nix
  ../../modules/theming/stylix.nix
  ../../modules/programs/tmux.nix
  ../../modules/programs/git.nix
  ../../modules/programs/bitwaden.nix
  ../../modules/programs/firefox.nix
  ../../modules/programs/chromium.nix
  ../../modules/programs/alacritty.nix
  ../../modules/programs/fastfetch.nix
  ../../modules/programs/scripts.nix
  ../../modules/programs/lsp-servers.nix
  ../../modules/programs/thunderbird.nix
]
